// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/nanoajax/nanoajax.d.ts
declare module nanoajax {
    interface RequestParameters {
        url: string;
        headers?: { [key: string]: string; };
        body?: string|FormData;
        method?: string;
        cors?: boolean;
    }

    interface Callback {
        (statusCode: number, response: string, request: XMLHttpRequest): any
    }

    export function ajax(params: RequestParameters, callback: Callback): XMLHttpRequest
}
